tags_replacement = {
    ".NET": ".NET",
    ".NET Core 5": ".NET Core 5",
    "3D": "3D",
    "ACSIA": "ACSIA",
    "AI": "AI/ML",
    "AI/ML": "AI/ML",
    "API Integrations": "API Integrations",
    "AR (Augmented Reality)": "AR (Augmented Reality)",
    "ASP.NET Core": "ASP.NET Core",
    "AWS": "AWS",
    "AWS Cloud": "AWS",
    "Accessible content": "Accessible content",
    "Aerospace": "Aerospace",
    "Agency": "Agency",
    "Agile": "Agile",
    "Agile Development": "Agile Development",
    "Agola": "Agola",
    "Airflow": "Airflow",
    "Alibaba Cloud": "Alibaba Cloud",
    "Android": "Android",
    "Angular": "Angular",
    "Ansible": "Ansible",
    "Apache Solr": "Apache Solr",
    "Apollo GraphQL Federation": "Apollo GraphQL Federation",
    "Application Maintenance": "Application Maintenance",
    "Application Security": "Application Security",
    "Architecture": "Architecture",
    "Arduino": "Arduino",
    "Arista Networks": "Arista Networks",
    "Asp.NET": "ASP.NET",
    "Atlassian": "Atlassian",
    "Authentication": "Authentication",
    "Authorization": "Authorization",
    "Automation": "Automation",
    "Azure": "Azure",
    "BI": "BI",
    "Big Data": "Big Data",
    "Big data": "Big Data",
    "BigQuery": "BigQuery",
    "Bitbucket": "Bitbucket",
    "Bitbucket pipelines": "Bitbucket pipelines",
    "Bitcoin": "Bitcoin",
    "Blazor": "Blazor",
    "Blender": "Blender",
    "Blockchain": "Blockchain",
    "Bootcamp": "Bootcamp",
    "Bootstrap": "Bootstrap",
    "Brand Identity": "Brand Identity",
    "Business Analyst": "Business Analyst",
    "Business Consulting": "Business Consulting",
    "Business Development": "Business Development",
    "Business Management": "Business Management",
    "Business Marketing": "Business Marketing",
    "C": "C",
    "C#": "C#/.NET",
    "C#/.NET": "C#/.NET",
    "C++": "C/C++",
    "C/C++": "C/C++",
    "CDK": "CDK",
    "CI/CD": "CI/CD",
    "CICD": "CI/CD",
    "CPaaS": "CPaaS",
    "CQRS": "CQRS",
    "CQRS Event-driven architectures": "CQRS",
    "CRM": "CRM",
    "CSS": "CSS",
    "Cassandra": "Cassandra",
    "Clean Architecture": "Clean Architecture",
    "Clojure": "Clojure",
    "Cloud": "Cloud",
    "Cloud Computing": "Cloud Computing",
    "Cloud Native": "Cloud Native",
    "Cloud Native Technologies": "Cloud Native Technologies",
    "Cloud native": "Cloud Native Technologies",
    "Cloud-native": "Cloud Native Technologies",
    "Cloudflare": "Cloudflare",
    "Coaching": "Coaching",
    "Code Review": "Code Review",
    "Computer Vision": "Computer Vision",
    "Computer vision": "Computer Vision",
    "Consul": "Consul",
    "Consultancy": "Consultancy",
    "Consulting": "Consulting",
    "Consulting company": "Consulting company",
    "Consumer insights": "Consumer insights",
    "Content Design": "Content Design",
    "Content design": "Content Design",
    "Continuous Delivery": "Continuous Delivery",
    "Continuous Integration": "Continuous Integration",
    "Cornerstone.js": "Cornerstone.js",
    "Cosmos": "Cosmos",
    "Cryptography": "Cryptography",
    "CyberSec": "CyberSec",
    "CyberSecurity": "CyberSec",
    "Cybersec": "CyberSec",
    "DDD": "DDD",
    "Dart": "Dart",
    "Data Analysis": "Data Analysis",
    "Data Engineering": "Data Engineering",
    "Data Intelligence": "Data Intelligence",
    "Data Science": "Data Science",
    "DataOps": "DataOps",
    "Databases": "Databases",
    "Databricks": "Databricks",
    "Datadog": "Datadog",
    "Debian": "Debian",
    "Deep Learning": "Deep Learning",
    "Design": "Design",
    "DevOps": "DevOps",
    "DevSecOps": "DevSecOps",
    "Digital Marketing": "Digital Marketing",
    "Digital Transformation": "Digital Transformation",
    "Digital marketing": "Digital Marketing",
    "DigitalOcean": "DigitalOcean",
    "Distributed Systems": "Distributed Systems",
    "Django": "Django",
    "Django REST framework": "Django REST framework",
    "Docker": "Docker",
    "Domain-Driven Design": "Domain-Driven Design",
    "Drupal": "Drupal",
    "DynamoDB": "DynamoDB",
    "E-learning": "E-learning",
    "EFK": "EFK",
    "ELK": "ELK",
    "ESP32": "ESP32",
    "Ecommerce": "Ecommerce",
    "EdTech": "EdTech",
    "Elastic": "Elastic",
    "ElasticSearch": "Elasticsearch",
    "Elasticsearch": "Elasticsearch",
    "Electron": "Electron",
    "Elixir": "Elixir/Erlang",
    "Elixir/Erlang": "Elixir/Erlang",
    "Elm": "Elm",
    "Embedded": "Embedded",
    "EmberJS": "EmberJS",
    "Enterprise solutions": "Enterprise solutions",
    "Ercole": "Ercole",
    "Ethereum": "Ethereum",
    "Event Driven Architecture": "Event Driven Architecture",
    "EventBridge": "EventBridge",
    "EventStorming": "EventStorming",
    "Events": "Events",
    "Express": "Express",
    "Falco": "Falco",
    "FastAPI": "FastAPI",
    "Figma": "Figma",
    "Fintech": "Fintech",
    "Firebase": "Firebase",
    "Flutter": "Flutter",
    "Flux": "Flux",
    "Full remote": "Full remote",
    "FullStackDev": "FullStackDev",
    "Fullstack": "Fullstack",
    "Functional Programming": "Functional Programming",
    "Functional Testing": "Functional Testing",
    "GCP": "GCP",
    "GCloud": "GCP",
    "GIS": "GIS",
    "GIS technologies": "GIS technologies",
    "GIT": "Git",
    "GO": "Go",
    "GStreamer": "GStreamer",
    "Gearman": "Gearman",
    "Geo-intelligence": "Geo-intelligence",
    "GeoServer": "GeoServer",
    "Geonode": "Geonode",
    "Git": "Git",
    "GitHub": "GitHub",
    "GitLab": "GitLab",
    "GitOps": "GitOps",
    "Go": "Go",
    "Golang": "Go",
    "Grails": "Grails",
    "GraphQL": "GraphQL",
    "HR": "HR",
    "HTML": "HTML",
    "HTMX": "HTMX",
    "Hardware Security": "Hardware Security",
    "Haskell": "Haskell",
    "Headless CMS": "Headless CMS",
    "HealthTech": "HealthTech",
    "Helm": "Helm",
    "Heroku": "Heroku",
    "Hibernate": "Hibernate",
    "IAM": "IAM",
    "IOS": "iOS",
    "IT Managed Services": "IT Managed Services",
    "IaC": "IaC",
    "Identity": "Identity",
    "Inclusive content": "Inclusive content",
    "Influencer Marketing": "Influencer Marketing",
    "Information architecture": "Information architecture",
    "Infosec": "Infosec",
    "Interaction Design": "Interaction Design",
    "Internet of Things": "Internet of Things",
    "IoT": "Internet of Things",
    "Ionic": "Ionic",
    "Istio": "Istio",
    "JAVA": "Java",
    "JS": "JavaScript",
    "Java": "Java",
    "Java/Maven": "Java/Maven",
    "JavaScript": "JavaScript",
    "Javascript": "JavaScript",
    "Javascript/Typescript": "JavaScript/TypeScript",
    "Jenkins": "Jenkins",
    "Jest": "Jest",
    "Jquery": "jQuery",
    "K8S": "Kubernetes",
    "K8s": "Kubernetes",
    "Kafka": "Kafka",
    "Kanban": "Kanban",
    "Kernel": "Kernel",
    "Kibana": "Kibana",
    "Kong": "Kong",
    "Kotlin": "Kotlin",
    "Kubernates": "Kubernetes",
    "Kubernetes": "Kubernetes",
    "Kubernetes operators": "Kubernetes operators",
    "LLama": "LLama",
    "Laravel": "Laravel",
    "Learning": "Learning",
    "Linux": "Linux",
    "Livewire": "Livewire",
    "LocalStack": "LocalStack",
    "Lumen": "Lumen",
    "MLOps": "MLOps",
    "MQTT": "MQTT",
    "MSSQL": "MSSQL",
    "MacOS": "MacOS",
    "Machine Learning": "AI/ML",
    "Magento": "Magento",
    "MapStore": "MapStore",
    "MariaDB": "MariaDB",
    "Marketing": "Marketing",
    "Matlab": "Matlab",
    "Maven": "Maven",
    "Memcached": "Memcached",
    "Mesa": "Mesa",
    "Micronaut": "Micronaut",
    "Microservice": "Microservice",
    "Microservices": "Microservices",
    "Microsoft Azure": "Microsoft Azure",
    "Migrations": "Migrations",
    "Mixed Reality": "Mixed Reality",
    "Mixpanel": "Mixpanel",
    "Mobile": "Mobile Development",
    "Mobile Apps": "Mobile Development",
    "Mobile Development": "Mobile Development",
    "Mobile Gaming": "Mobile Gaming",
    "Mobile app": "Mobile Development",
    "Mobx": "MobX",
    "MongoDB": "MongoDB",
    "MongoDb": "MongoDB",
    "Multimedia": "Multimedia",
    "MySQL": "MySQL",
    "Mysql": "MySQL",
    "Nakama": "Nakama",
    "Native Mobile Development": "Native Mobile Development",
    "Nativescript": "NativeScript",
    "Natural Language Processing": "Natural Language Processing",
    "Navision": "Navision",
    "Nest": "NestJS",
    "NestJS": "NestJS",
    "Nestjs": "NestJS",
    "Netlify": "Netlify",
    "Newsletter": "Newsletter",
    "Next.js": "Next.js",
    "NextJS": "Next.js",
    "Nginx": "Nginx",
    "NginxPlus": "NginxPlus",
    "NoSQL": "NoSQL",
    "NoSql": "NoSQL",
    "Node": "Node.js",
    "Node.js": "Node.js",
    "Node.js (Nest.js)": "Nest.js",
    "Node.js/React": "Node.js/React",
    "NodeJS": "Node.js",
    "NodeJs": "Node.js",
    "Notion": "Notion",
    "Nuxt.js": "Nuxt.js",
    "NuxtJS": "Nuxt.js",
    "OSINT": "OSINT",
    "OWL": "OWL",
    "Odoo": "Odoo",
    "Online Trainings": "Online Trainings",
    "Open Source": "Open Source",
    "Open Source development": "Open Source",
    "Open source": "Open Source",
    "OpenAI": "OpenAI",
    "OpenID Connect": "OpenID Connect",
    "OpenShift": "OpenShift",
    "OpenStack": "OpenStack",
    "Openshift": "OpenShift",
    "Opensource": "Open Source",
    "Openstack": "OpenStack",
    "Oracle": "Oracle",
    "OracleSQL": "OracleSQL",
    "Organization Design": "Organization Design",
    "PHP": "PHP",
    "PHP (Laravel)": "PHP (Laravel)",
    "Palo Alto Networks": "Palo Alto Networks",
    "Penetration Test": "Penetration Test",
    "Penetration Testing": "Penetration Testing",
    "Pentest": "Penetration Test",
    "Phonegap": "PhoneGap",
    "Platform Engineering": "Platform Engineering",
    "Plone": "Plone",
    "PosgtgreSQL": "PostgreSQL",
    "PostgreSQL": "PostgreSQL",
    "Postgres": "PostgreSQL",
    "PostgresQL": "PostgreSQL",
    "PowerBI": "PowerBI",
    "PowerShell": "PowerShell",
    "Powershell": "PowerShell",
    "PrestaShop": "PrestaShop",
    "Prometheus": "Prometheus",
    "Provisioning": "Provisioning",
    "Pulumi": "Pulumi",
    "Python": "Python",
    "QA": "QA",
    "Qt": "Qt",
    "Quarkus": "Quarkus",
    "Quasar": "Quasar",
    "R": "R",
    "REST": "REST",
    "REST API": "REST API",
    "REST Api": "REST API",
    "RabbitMQ": "RabbitMQ",
    "Rails": "Ruby on Rails",
    "Rancher": "Rancher",
    "React": "React",
    "React Native": "React Native",
    "React.js": "React",
    "ReactJS": "React",
    "ReactNative": "React Native",
    "Red Hat OpenShift": "OpenShift",
    "Red Teaming": "Red Teaming",
    "Redis": "Redis",
    "Redux": "Redux",
    "Remix": "Remix",
    "Ruby": "Ruby on Rails",
    "Ruby On Rails": "Ruby on Rails",
    "Ruby on Rails": "Ruby on Rails",
    "Ruby on rails": "Ruby on Rails",
    "Rust": "Rust",
    "SAML": "SAML",
    "SAP": "SAP",
    "SASS": "Sass",
    "SCRUM": "Scrum",
    "SEM": "SEM",
    "SEO": "SEO",
    "SEO Agency": "SEO Agency",
    "SOC": "SOC",
    "SPID": "SPID",
    "SQL": "SQL",
    "SQL Server": "SQL Server",
    "SQL server": "SQL Server",
    "SQLServer": "SQL Server",
    "SRE": "SRE",
    "SYNwall": "SYNwall",
    "SaaS": "SaaS",
    "Salesforce": "Salesforce",
    "Salesforce Commerce Cloud": "Salesforce Commerce Cloud",
    "SaltStack": "SaltStack",
    "Sass": "Sass",
    "Scala": "Scala",
    "Scrum": "Scrum",
    "SecOps": "SecOps",
    "Security": "Security",
    "Security Research": "Security Research",
    "Serverless": "Serverless",
    "Serverless Big Data": "Serverless Big Data",
    "Service Mesh": "Service Mesh",
    "Shopify": "Shopify",
    "Sitecore": "Sitecore",
    "Snowflake": "Snowflake",
    "Social Media Management": "Social Media Management",
    "Software Development": "Software Development",
    "Solidity": "Solidity",
    "Spark": "Spark",
    "Spring": "Spring Boot",
    "Spring Boot": "Spring Boot",
    "Startup Builder": "Startup Builder",
    "Stolon": "Stolon",
    "Strapi": "Strapi",
    "Svelte": "Svelte",
    "Swift": "Swift",
    "Swifth": "Swift",
    "Symfony": "Symfony",
    "Symphony": "Symfony",
    "TDD": "TDD",
    "TDD/BDD": "TDD/BDD",
    "TailwindCSS": "Tailwind CSS",
    "Tailwindcss": "Tailwind CSS",
    "TensorFlow": "TensorFlow",
    "Terraform": "Terraform",
    "Test Driven Development": "Test Driven Development",
    "Three.js": "Three.js",
    "ThreeJs": "Three.js",
    "TimeScale": "TimeScale",
    "Tomcat": "Tomcat",
    "Training": "Training",
    "TrinoDB": "TrinoDB",
    "Troubleshooting": "Troubleshooting",
    "TypeScript": "TypeScript",
    "Typescript": "TypeScript",
    "UAT": "UAT",
    "UI": "UX/UI",
    "UI Design": "UX/UI",
    "UI/UX Design": "UX/UI",
    "UX": "UX/UI",
    "UX Design": "UX/UI",
    "UX Writing": "UX/UI",
    "UX/UI": "UX/UI",
    "Unity": "Unity",
    "Unity 3D": "Unity",
    "Unity3D": "Unity",
    "Unreal": "Unreal",
    "UnrealEngine": "Unreal",
    "User Research": "User Research",
    "VMWare": "VMware",
    "VMware": "VMware",
    "VR (Virtual Reality)": "VR (Virtual Reality)",
    "VTK": "VTK",
    "Venture capital": "Venture capital",
    "Vue": "Vue.js",
    "Vue (Nuxt.js)": "Vue.js (Nuxt.js)",
    "Vue JS": "Vue.js",
    "Vue.js": "Vue.js",
    "VueJS": "Vue.js",
    "VueJs": "Vue.js",
    "Vulkan": "Vulkan",
    "Vulnerability Assessment": "Vulnerability Assessment",
    "WASM": "WASM",
    "Web Development": "Web Development",
    "WebAssembly": "WebAssembly",
    "WebGL": "WebGL",
    "WebGl": "WebGL",
    "WebRTC": "WebRTC",
    "Wellbeing": "Wellbeing",
    "Windows": "Windows",
    "WooCommerce": "WooCommerce",
    "Wordpress": "WordPress",
    "Xamarin": "Xamarin",
    "Yii": "Yii",
    "eBPF": "eBPF",
    "fintech": "Fintech",
    "fp-ts": "fp-ts",
    "gRPC": "gRPC",
    "htmx": "HTMX",
    "hyperscript": "Hyperscript",
    "iOS": "iOS",
    "marketing": "Marketing",
    "morfeojs": "morfeo.js",
    "nextjs": "Next.js",
    "nocode": "NoCode",
    "shopify": "Shopify",
    "terraform": "Terraform",
    "unknown": "unknown"
}